// Modification Copyright 2024 The Wemix Authors
//
// This file is derived from quorum/consensus/istanbul/qbft/engine/engine_test.go (2024.07.25).
// Modified and improved for the wemix development.

package qbftengine

import (
	"bytes"
	"crypto/ecdsa"
	"math/big"
	"reflect"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/consensus"
	"github.com/ethereum/go-ethereum/consensus/qbft"
	qbftcommon "github.com/ethereum/go-ethereum/consensus/qbft/common"
	qbftcore "github.com/ethereum/go-ethereum/consensus/qbft/core"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/params"
)

// RLP data can be generated by using TestGeneratingGenesisExtra in testutils package
// Notice that default genesis extra data is used
//
//   go test -v -count 1 ./consensus/qbft/testutils -run TestGeneratingGenesisExtra

func TestPrepareExtra(t *testing.T) {
	expectedResult := hexutil.MustDecode("0xe7a0000000000000000000000000000000000000000000000000000000000000000080c0c0c0c0c0")

	h := &types.Header{}
	err := ApplyHeaderQBFTExtra(
		h,
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}
	if !reflect.DeepEqual(h.Extra, expectedResult) {
		t.Errorf("payload mismatch: have %v, want %v", hexutil.Encode(h.Extra), hexutil.Encode(expectedResult))
	}
}

func TestWriteCommittedSeals(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf8778080c0c0c0c0f86ff868d99444add0ec310f115a0e603b2d7db9f067778eaf8a831cfde0d994294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212831cfde0d9946beaaed781d2d2ab6350f5c4566a2c6eaac407a6831cfde0d9948be76812f765c24641ec63dc2852b378aba2b440831cfde0c480010203")
	expectedCommittedSeal := append([]byte{1, 2, 3}, bytes.Repeat([]byte{0x00}, types.IstanbulExtraSeal-3)...)
	expectedIstExtra := &types.QBFTExtra{
		VanityData:        []byte{},
		CommittedSeal:     [][]byte{expectedCommittedSeal},
		PreparedSeal:      [][]byte{},
		PrevCommittedSeal: [][]byte{},
		PrevPreparedSeal:  [][]byte{},
		Round:             0,
		EpochInfo: &types.EpochInfo{
			Stakers: []*types.Staker{
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x44add0ec310f115a0e603b2d7db9f067778eaf8a")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x6beaaed781d2d2ab6350f5c4566a2c6eaac407a6")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x8be76812f765c24641ec63dc2852b378aba2b440")), Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
		},
	}

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	err := ApplyHeaderQBFTExtra(
		h,
		writeCommittedSeals([][]byte{expectedCommittedSeal}),
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}

	// verify qbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra, expectedIstExtra)
	}

	// invalid seal
	unexpectedCommittedSeal := append(expectedCommittedSeal, make([]byte, 1)...)
	err = ApplyHeaderQBFTExtra(
		h,
		writeCommittedSeals([][]byte{unexpectedCommittedSeal}),
	)
	if err != qbftcommon.ErrInvalidCommittedSeals {
		t.Errorf("error mismatch: have %v, want %v", err, qbftcommon.ErrInvalidCommittedSeals)
	}
}

func TestWritePreparedSeals(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf8778080c0c0c0c0f86ff868d99444add0ec310f115a0e603b2d7db9f067778eaf8a831cfde0d994294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212831cfde0d9946beaaed781d2d2ab6350f5c4566a2c6eaac407a6831cfde0d9948be76812f765c24641ec63dc2852b378aba2b440831cfde0c480010203")
	expectedPreparedSeal := append([]byte{1, 2, 3}, bytes.Repeat([]byte{0x00}, types.IstanbulExtraSeal-3)...)
	expectedIstExtra := &types.QBFTExtra{
		VanityData:        []byte{},
		CommittedSeal:     [][]byte{},
		PreparedSeal:      [][]byte{expectedPreparedSeal},
		PrevCommittedSeal: [][]byte{},
		PrevPreparedSeal:  [][]byte{},
		Round:             0,
		EpochInfo: &types.EpochInfo{
			Stakers: []*types.Staker{
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x44add0ec310f115a0e603b2d7db9f067778eaf8a")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x6beaaed781d2d2ab6350f5c4566a2c6eaac407a6")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x8be76812f765c24641ec63dc2852b378aba2b440")), Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
		},
	}

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	err := ApplyHeaderQBFTExtra(
		h,
		writePreparedSeals([][]byte{expectedPreparedSeal}),
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}

	// verify qbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra, expectedIstExtra)
	}

	// invalid seal
	unexpectedPreparedSeal := append(expectedPreparedSeal, make([]byte, 1)...)
	err = ApplyHeaderQBFTExtra(
		h,
		writePreparedSeals([][]byte{unexpectedPreparedSeal}),
	)
	if err != qbftcommon.ErrInvalidPreparedSeals {
		t.Errorf("error mismatch: have %v, want %v", err, qbftcommon.ErrInvalidPreparedSeals)
	}
}

func TestWriteRoundNumber(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf8778080c0c0c0c0f86ff868d99444add0ec310f115a0e603b2d7db9f067778eaf8a831cfde0d994294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212831cfde0d9946beaaed781d2d2ab6350f5c4566a2c6eaac407a6831cfde0d9948be76812f765c24641ec63dc2852b378aba2b440831cfde0c480010203")
	expectedIstExtra := &types.QBFTExtra{
		VanityData:        []byte{},
		CommittedSeal:     [][]byte{},
		PreparedSeal:      [][]byte{},
		PrevCommittedSeal: [][]byte{},
		PrevPreparedSeal:  [][]byte{},
		Round:             5,
		EpochInfo: &types.EpochInfo{
			Stakers: []*types.Staker{
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x44add0ec310f115a0e603b2d7db9f067778eaf8a")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x6beaaed781d2d2ab6350f5c4566a2c6eaac407a6")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x8be76812f765c24641ec63dc2852b378aba2b440")), Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
		},
	}

	var expectedErr error

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	err := ApplyHeaderQBFTExtra(
		h,
		writeRoundNumber(big.NewInt(5)),
	)
	if err != expectedErr {
		t.Errorf("error mismatch: have %v, want %v", err, expectedErr)
	}

	// verify qbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra.VanityData, expectedIstExtra.VanityData)
	}
}

type fakeChain struct {
	headers []*types.Header
}

var _ consensus.ChainHeaderReader = (*fakeChain)(nil)

func (f *fakeChain) Config() *params.ChainConfig  { return nil }
func (f *fakeChain) CurrentHeader() *types.Header { return nil }
func (f *fakeChain) GetHeader(hash common.Hash, number uint64) *types.Header {
	return f.headers[number]
}
func (f *fakeChain) GetHeaderByNumber(number uint64) *types.Header  { return nil }
func (f *fakeChain) GetHeaderByHash(hash common.Hash) *types.Header { return nil }
func (f *fakeChain) GetTd(hash common.Hash, number uint64) *big.Int { return nil }

func (f *fakeChain) insertHeader(h *types.Header) {
	f.headers = append(f.headers, h)
}

type account struct {
	key  *ecdsa.PrivateKey
	addr common.Address
}

func newAccounts(n int) (accounts []account) {
	for i := 0; i < n; i++ {
		key, _ := crypto.GenerateKey()
		addr := crypto.PubkeyToAddress(key.PublicKey)
		accounts = append(accounts, account{key: key, addr: addr})
	}
	return accounts
}

// TODO: WEMIX chain
// TODO: fake gov contract
// TODO: change epoch, staker/validator set dynamically
func TestDiligence(t *testing.T) {
	var testCases = []struct {
		name           string
		totValidators  int
		proposers      []int
		preparedSeals  [][]int
		committedSeals [][]int
		expDiligences  [][]uint64
	}{
		{
			"All validators include seals completely (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1910000, 1910000, 1910000},
				{1910000, 1910000, 1910000}, {1910000, 1910000, 1910000}, {1919000, 1919000, 1919000},
			},
		},
		{
			"Some validators miss seals for other validators (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{
				{0, 1}, {0, 1}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{0, 1, 2}, {0, 1}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1893333, 1876666, 1860000},
				{1893333, 1876666, 1860000}, {1893333, 1876666, 1860000}, {1903999, 1888999, 1874000},
			},
		},
		{
			"Some validators miss own seals (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{
				{1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1843333, 1910000, 1910000},
				{1843333, 1910000, 1910000}, {1843333, 1910000, 1910000}, {1858999, 1919000, 1885666},
			},
		},
		{
			"Validators propose different number of blocks (2 validators, 3 blocks / epoch)",
			2,
			[]int{0, 1, 0, 1, 0, 1},
			[][]int{
				{0, 1}, {0, 1}, {0, 1},
				{0, 1}, {0, 1}, {0, 1},
			},
			[][]int{
				{0, 1}, {0, 1}, {0, 1},
				{0, 1}, {0, 1}, {0, 1},
			},
			[][]uint64{
				{1900000, 1900000}, {1900000, 1900000}, {1910000, 1910000},
				{1910000, 1910000}, {1910000, 1910000}, {1919000, 1919000},
			},
		},
		{
			"No validators include seals (2 validators, 3 blocks / epoch)",
			2,
			[]int{0, 1, 0, 1, 0, 1},
			[][]int{
				{}, {}, {},
				{}, {}, {},
			},
			[][]int{
				{}, {}, {},
				{}, {}, {},
			},
			[][]uint64{
				{1900000, 1900000}, {1900000, 1900000}, {1710000, 1710000},
				{1710000, 1710000}, {1710000, 1710000}, {1539000, 1539000},
			},
		},
		{
			"Some validators are excluded to propose blocks (4 validators, 3 blocks / epoch)",
			4,
			[]int{0, 1, 2, 3, 0, 1},
			[][]int{
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
			},
			[][]int{
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
			},
			[][]uint64{
				{1900000, 1900000, 1900000, 1900000}, {1900000, 1900000, 1900000, 1900000}, {1910000, 1910000, 1910000, 1810000},
				{1910000, 1910000, 1910000, 1810000}, {1910000, 1910000, 1910000, 1810000}, {1919000, 1919000, 1819000, 1829000},
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			var parent *types.Header

			// Setup validators
			signers := newAccounts(tc.totValidators)
			var validators []common.Address
			for _, s := range signers {
				validators = append(validators, s.addr)
			}

			// Setup genesis
			c := new(fakeChain)
			engine := NewEngine(&qbft.Config{Validators: validators}, common.Address{}, nil)
			parent = makeGenesis(signers)
			c.insertHeader(parent)

			for i, author := range tc.proposers {
				var preparedSeals, committedSeals [][]byte

				h := makeHeader(parent)
				h.Coinbase = signers[author].addr

				// Fill prev seals
				for _, s := range tc.preparedSeals[i] {
					preparedSeals = append(preparedSeals, makePrepareSeal(parent, signers[s]))
				}
				for _, s := range tc.committedSeals[i] {
					committedSeals = append(committedSeals, makeCommitSeal(parent, signers[s]))
				}
				ApplyHeaderQBFTExtra(
					h,
					WritePrevPreparedSeal(preparedSeals),
					WritePrevCommittedSeal(committedSeals),
				)

				// Fake finalize block
				newEpoch := engine.buildEpochInfo(c, h)
				ApplyHeaderQBFTExtra(h, WriteEpochInfo(newEpoch))
				if newEpoch != nil && !engine.IsEpochBlock(h) {
					t.Errorf("expected epoch info to be nil")
				}

				c.insertHeader(h)
				parent = h

				// Get nearest epoch block
				var eb *types.Header
				if newEpoch != nil {
					eb = h
				} else {
					eb = engine.GetEpochBlock(c, h)
				}
				qbftExtra, _ := types.ExtractQBFTExtra(eb)

				//t.Log("epoch info", "h.Number", h.Number, "validators", qbftExtra.EpochInfo.Validators)
				//for j, staker := range qbftExtra.EpochInfo.Stakers {
				//	t.Log("staker", "j", j, "address", staker.Addr, "diligence", staker.Diligence)
				//}

				// Validate diligences
				for j, d := range tc.expDiligences[i] {
					staker := qbftExtra.EpochInfo.Stakers[j]
					if d != staker.Diligence {
						t.Errorf("expected %d, got %d for staker %d", d, staker.Diligence, j)
					}
				}
			}
		})
	}
}

func makeGenesis(signers []account) *types.Header {
	header := &types.Header{
		Number:     big.NewInt(0),
		Time:       uint64(time.Now().UnixNano()),
		Difficulty: types.QBFTDefaultDifficulty,
	}

	e := new(types.EpochInfo)
	for i, s := range signers {
		e.Stakers = append(e.Stakers, &types.Staker{Addr: s.addr, Diligence: 1900000})
		e.Validators = append(e.Validators, uint32(i))
	}
	ApplyHeaderQBFTExtra(header, WriteEpochInfo(e))
	return header
}

func makeHeader(parent *types.Header) *types.Header {
	header := types.CopyHeader(parent)
	header.Number.Add(header.Number, big.NewInt(1))
	header.Time = uint64(time.Now().UnixNano())

	return header
}

func makePrepareSeal(h *types.Header, node account) []byte {
	seal, err := crypto.Sign(qbftcore.PrepareSeal(h, 0, qbftcore.SealTypePrepare), node.key)
	if err != nil {
		panic(err)
	}
	return seal
}

func makeCommitSeal(h *types.Header, node account) []byte {
	seal, err := crypto.Sign(qbftcore.PrepareSeal(h, 0, qbftcore.SealTypeCommit), node.key)
	if err != nil {
		panic(err)
	}
	return seal
}
