// Modification Copyright 2024 The Wemix Authors
//
// This file is derived from quorum/consensus/istanbul/qbft/engine/engine_test.go (2024.07.25).
// Modified and improved for the wemix development.

package qbftengine

import (
	"bytes"
	"crypto/ecdsa"
	"errors"
	"math/big"
	"reflect"
	"slices"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/common/math"
	"github.com/ethereum/go-ethereum/consensus"
	"github.com/ethereum/go-ethereum/consensus/qbft"
	qbftcommon "github.com/ethereum/go-ethereum/consensus/qbft/common"
	qbftcore "github.com/ethereum/go-ethereum/consensus/qbft/core"
	"github.com/ethereum/go-ethereum/core/rawdb"
	"github.com/ethereum/go-ethereum/core/state"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/log"
	"github.com/ethereum/go-ethereum/params"
	govwbft "github.com/ethereum/go-ethereum/wemixgov/governance-wbft"
)

// RLP data can be generated by using TestGeneratingGenesisExtra in testutils package
// Notice that default genesis extra data is used
//
//   go test -v -count 1 ./consensus/qbft/testutils -run TestGeneratingGenesisExtra

func TestPrepareExtra(t *testing.T) {
	expectedResult := hexutil.MustDecode("0xe8a0000000000000000000000000000000000000000000000000000000000000000080c0c080c0c0c0")

	h := &types.Header{}
	err := ApplyHeaderQBFTExtra(
		h,
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}
	if !reflect.DeepEqual(h.Extra, expectedResult) {
		t.Errorf("payload mismatch: have %v, want %v", hexutil.Encode(h.Extra), hexutil.Encode(expectedResult))
	}
}

func TestWriteCommittedSeals(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf8788080c0c080c0c0f86ff868d99444add0ec310f115a0e603b2d7db9f067778eaf8a831cfde0d994294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212831cfde0d9946beaaed781d2d2ab6350f5c4566a2c6eaac407a6831cfde0d9948be76812f765c24641ec63dc2852b378aba2b440831cfde0c480010203")
	expectedCommittedSeal := append([]byte{1, 2, 3}, bytes.Repeat([]byte{0x00}, types.IstanbulExtraSeal-3)...)
	expectedIstExtra := &types.QBFTExtra{
		VanityData:        []byte{},
		PrevRound:         0,
		PrevCommittedSeal: [][]byte{},
		PrevPreparedSeal:  [][]byte{},
		Round:             0,
		CommittedSeal:     [][]byte{expectedCommittedSeal},
		PreparedSeal:      [][]byte{},
		EpochInfo: &types.EpochInfo{
			Stakers: []*types.Staker{
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x44add0ec310f115a0e603b2d7db9f067778eaf8a")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x6beaaed781d2d2ab6350f5c4566a2c6eaac407a6")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x8be76812f765c24641ec63dc2852b378aba2b440")), Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
		},
	}

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	err := ApplyHeaderQBFTExtra(
		h,
		writeCommittedSeals([][]byte{expectedCommittedSeal}),
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}

	// verify qbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra, expectedIstExtra)
	}

	// invalid seal
	unexpectedCommittedSeal := append(expectedCommittedSeal, make([]byte, 1)...)
	err = ApplyHeaderQBFTExtra(
		h,
		writeCommittedSeals([][]byte{unexpectedCommittedSeal}),
	)
	if err != qbftcommon.ErrInvalidCommittedSeals {
		t.Errorf("error mismatch: have %v, want %v", err, qbftcommon.ErrInvalidCommittedSeals)
	}
}

func TestWritePreparedSeals(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf8788080c0c080c0c0f86ff868d99444add0ec310f115a0e603b2d7db9f067778eaf8a831cfde0d994294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212831cfde0d9946beaaed781d2d2ab6350f5c4566a2c6eaac407a6831cfde0d9948be76812f765c24641ec63dc2852b378aba2b440831cfde0c480010203")
	expectedPreparedSeal := append([]byte{1, 2, 3}, bytes.Repeat([]byte{0x00}, types.IstanbulExtraSeal-3)...)
	expectedIstExtra := &types.QBFTExtra{
		VanityData:        []byte{},
		PrevRound:         0,
		PrevCommittedSeal: [][]byte{},
		PrevPreparedSeal:  [][]byte{},
		Round:             0,
		CommittedSeal:     [][]byte{},
		PreparedSeal:      [][]byte{expectedPreparedSeal},
		EpochInfo: &types.EpochInfo{
			Stakers: []*types.Staker{
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x44add0ec310f115a0e603b2d7db9f067778eaf8a")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x6beaaed781d2d2ab6350f5c4566a2c6eaac407a6")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x8be76812f765c24641ec63dc2852b378aba2b440")), Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
		},
	}

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	err := ApplyHeaderQBFTExtra(
		h,
		writePreparedSeals([][]byte{expectedPreparedSeal}),
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}

	// verify qbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra, expectedIstExtra)
	}

	// invalid seal
	unexpectedPreparedSeal := append(expectedPreparedSeal, make([]byte, 1)...)
	err = ApplyHeaderQBFTExtra(
		h,
		writePreparedSeals([][]byte{unexpectedPreparedSeal}),
	)
	if err != qbftcommon.ErrInvalidPreparedSeals {
		t.Errorf("error mismatch: have %v, want %v", err, qbftcommon.ErrInvalidPreparedSeals)
	}
}

func TestWriteRoundNumber(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf8788080c0c080c0c0f86ff868d99444add0ec310f115a0e603b2d7db9f067778eaf8a831cfde0d994294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212831cfde0d9946beaaed781d2d2ab6350f5c4566a2c6eaac407a6831cfde0d9948be76812f765c24641ec63dc2852b378aba2b440831cfde0c480010203")
	expectedIstExtra := &types.QBFTExtra{
		VanityData:        []byte{},
		PrevRound:         0,
		PrevCommittedSeal: [][]byte{},
		PrevPreparedSeal:  [][]byte{},
		Round:             0,
		CommittedSeal:     [][]byte{},
		PreparedSeal:      [][]byte{},
		EpochInfo: &types.EpochInfo{
			Stakers: []*types.Staker{
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x44add0ec310f115a0e603b2d7db9f067778eaf8a")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x6beaaed781d2d2ab6350f5c4566a2c6eaac407a6")), Diligence: 1_900_000},
				{Addr: common.BytesToAddress(hexutil.MustDecode("0x8be76812f765c24641ec63dc2852b378aba2b440")), Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
		},
	}

	var expectedErr error

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	err := ApplyHeaderQBFTExtra(
		h,
		writeRoundNumber(big.NewInt(5)),
	)
	if err != expectedErr {
		t.Errorf("error mismatch: have %v, want %v", err, expectedErr)
	}

	// verify qbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if istExtra.Round != 5 {
		t.Errorf("writing round does not effected")
	}
	istExtra.Round = expectedIstExtra.Round
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra.VanityData, expectedIstExtra.VanityData)
	}
}

type fakeChain struct {
	chainConfig *params.ChainConfig
	headers     []*types.Header
}

var _ consensus.ChainHeaderReader = (*fakeChain)(nil)

func (f *fakeChain) Config() *params.ChainConfig {
	return f.chainConfig
}
func (f *fakeChain) CurrentHeader() *types.Header { return nil }
func (f *fakeChain) GetHeader(hash common.Hash, number uint64) *types.Header {
	return f.headers[number]
}
func (f *fakeChain) GetHeaderByNumber(number uint64) *types.Header  { return nil }
func (f *fakeChain) GetHeaderByHash(hash common.Hash) *types.Header { return nil }
func (f *fakeChain) GetTd(hash common.Hash, number uint64) *big.Int { return nil }

func (f *fakeChain) insertHeader(h *types.Header) {
	f.headers = append(f.headers, h)
}

type account struct {
	key  *ecdsa.PrivateKey
	addr common.Address
}

func newAccounts(n int) (accounts []account) {
	for i := 0; i < n; i++ {
		key, _ := crypto.GenerateKey()
		addr := crypto.PubkeyToAddress(key.PublicKey)
		accounts = append(accounts, account{key: key, addr: addr})
	}

	return accounts
}

// TODO: WEMIX chain
func TestEpochInfo(t *testing.T) {
	var testCases = []struct {
		name           string
		totValidators  int
		proposers      []int
		preparedSeals  [][]int
		committedSeals [][]int
		expDiligences  [][]uint64
	}{
		{
			"All validators include seals completely (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1910000, 1910000, 1910000},
				{1910000, 1910000, 1910000}, {1910000, 1910000, 1910000}, {1919000, 1919000, 1919000},
			},
		},
		{
			"Some validators miss seals for other validators (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{
				{0, 1}, {0, 1}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{0, 1, 2}, {0, 1}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1893333, 1876666, 1860000},
				{1893333, 1876666, 1860000}, {1893333, 1876666, 1860000}, {1903999, 1888999, 1874000},
			},
		},
		{
			"Some validators miss own seals (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{
				{1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1843333, 1910000, 1910000},
				{1843333, 1910000, 1910000}, {1843333, 1910000, 1910000}, {1858999, 1919000, 1885666},
			},
		},
		{
			"Validators propose multiple number of blocks (2 validators, 3 blocks / epoch)",
			2,
			[]int{0, 1, 0, 1, 0, 1},
			[][]int{
				{0, 1}, {0, 1}, {0, 1},
				{0, 1}, {0, 1}, {0, 1},
			},
			[][]int{
				{0, 1}, {0, 1}, {0, 1},
				{0, 1}, {0, 1}, {0, 1},
			},
			[][]uint64{
				{1900000, 1900000}, {1900000, 1900000}, {1910000, 1910000},
				{1910000, 1910000}, {1910000, 1910000}, {1919000, 1919000},
			},
		},
		{
			"Some validators are excluded to propose blocks (4 validators, 3 blocks / epoch)",
			4,
			[]int{0, 1, 2, 3, 0, 1},
			[][]int{
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
			},
			[][]int{
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
			},
			[][]uint64{
				{1900000, 1900000, 1900000, 1900000}, {1900000, 1900000, 1900000, 1900000}, {1910000, 1910000, 1910000, 1910000},
				{1910000, 1910000, 1910000, 1910000}, {1910000, 1910000, 1910000, 1910000}, {1919000, 1919000, 1919000, 1919000},
			},
		},
		{
			"Round changes occur (3 validators, 3 blocks / epoch)",
			3,
			[]int{2, 1, 0, 2, 1, 1}, // 0, 1, "2", 0, "1", 2, "0", 1, "2", 0, "1", 2, 0, "1"
			[][]int{
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1843333, 1860000, 1860000},
				{1843333, 1860000, 1860000}, {1843333, 1860000, 1860000}, {1758999, 1840666, 1824000},
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			var parent *types.Header

			// Setup validators
			signers := newAccounts(tc.totValidators)
			var validators []common.Address
			for _, s := range signers {
				validators = append(validators, s.addr)
			}

			// Setup test chain genesis
			c := new(fakeChain)
			c.chainConfig = params.TestChainConfig
			engine := NewEngine(&qbft.Config{
				Validators:     validators,
				ProposerPolicy: qbft.NewRoundRobinProposerPolicy(),
				Epoch:          3,
			}, common.Address{}, nil)
			parent = makeGenesis(signers)
			c.insertHeader(parent)

			// Finalize and insert blocks based according to test case
			for i, author := range tc.proposers {
				var preparedSeals, committedSeals [][]byte

				h := makeHeader(parent)
				h.Coinbase = signers[author].addr

				// Fill prev seals
				round := uint32((i + 1) % 4) // deterministic random round
				for _, s := range tc.preparedSeals[i] {
					preparedSeals = append(preparedSeals, makePrepareSeal(parent, signers[s], round))
				}
				for _, s := range tc.committedSeals[i] {
					committedSeals = append(committedSeals, makeCommitSeal(parent, signers[s], round))
				}
				ApplyHeaderQBFTExtra(
					h,
					WritePrevSeals(round, preparedSeals, committedSeals),
				)

				// Build epoch info
				newEpoch := engine.buildEpochInfo(c, h, nil)
				ApplyHeaderQBFTExtra(h, WriteEpochInfo(newEpoch))
				isEpoch, _, _ := engine.IsEpochBlockNumber(c.chainConfig, h.Number)
				if newEpoch != nil && !isEpoch {
					t.Errorf("expected epoch info to be nil")
				}

				c.insertHeader(h)
				parent = h

				// Get nearest epoch block
				var eb *types.Header
				if newEpoch != nil {
					eb = h
				} else {
					eb = getEpochBlock(engine, c, h)
				}
				qbftExtra, _ := types.ExtractQBFTExtra(eb)

				//t.Log("epoch info", "h.Number", h.Number, "validators", qbftExtra.EpochInfo.Validators)
				//for j, staker := range qbftExtra.EpochInfo.Stakers {
				//	t.Log("staker", "j", j, "address", staker.Addr, "diligence", staker.Diligence)
				//}

				// Validate diligences
				for j, d := range tc.expDiligences[i] {
					staker := qbftExtra.EpochInfo.Stakers[j]
					if d != staker.Diligence {
						t.Errorf("expected diligence mismatch for staker %d: have %d, want %d", j, staker.Diligence, d)
					}
				}
			}
		})
	}
}

// Test distributing rewards without rewards for consensus proof (using Brioche config)
func TestDistributeRewardsForZeroStakes(t *testing.T) {
	var testCases = []struct {
		name       string
		qbftConfig *qbft.Config
		expReward  uint64
	}{
		{
			"Proposer gets all rewards",
			&qbft.Config{
				ProposerPolicy: qbft.NewRoundRobinProposerPolicy(),
				Epoch:          1,
			},
			1000000000000000000,
		},
		{
			"Proposer and 2 beneficiaries share rewards",
			&qbft.Config{
				ProposerPolicy: qbft.NewRoundRobinProposerPolicy(),
				Epoch:          1,
				BlockRewardBeneficiary: &params.BeneficiaryInfo{
					Denominator: 10000,
					Beneficiaries: []*params.Beneficiary{
						{Name: "B1", Addr: common.Address{0x1}, Numerator: 2000},
						{Name: "B2", Addr: common.Address{0x2}, Numerator: 3500},
					},
				},
			},
			450000000000000000,
		},
		{
			"Beneficiaries gets all rewards",
			&qbft.Config{
				ProposerPolicy: qbft.NewRoundRobinProposerPolicy(),
				Epoch:          1,
				BlockRewardBeneficiary: &params.BeneficiaryInfo{
					Denominator: 10000,
					Beneficiaries: []*params.Beneficiary{
						{Name: "B1", Addr: common.Address{0x1}, Numerator: 2000},
						{Name: "B2", Addr: common.Address{0x2}, Numerator: 8000},
					},
				},
			},
			0,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Setup validators
			signers := newAccounts(4)

			// Setup test chain genesis
			c := new(fakeChain)
			c.chainConfig = params.TestChainConfig
			c.chainConfig.QBFT.BlockReward = (*math.HexOrDecimal256)(big.NewInt(params.Ether))
			state, _ := state.New(types.EmptyRootHash, state.NewDatabase(rawdb.NewMemoryDatabase()), nil)
			engine := NewEngine(tc.qbftConfig, common.Address{}, nil)
			parent := makeGenesis(signers)
			c.insertHeader(parent)

			// Proposer makes a block
			proposer := signers[0].addr
			h := makeHeader(parent)
			h.Coinbase = proposer
			c.insertHeader(h)

			engine.accumulateRewards(c, state, h)

			// Validate rewards
			bal := state.GetBalance(proposer)
			if bal.CmpUint64(tc.expReward) != 0 {
				t.Errorf("expected reward mismatch for validator: have %v, want %v", bal, tc.expReward)
			}
		})
	}
}

// Test distributing rewards only for consensus proof (using non-Brioche config)
func TestDistributeRewardsOnlyForStakes(t *testing.T) {
	var testCases = []struct {
		name          string
		totValidators int
		qbftConfig    *qbft.Config
		stakes        []*big.Int
		expRewards    []uint64
	}{
		{
			"Stakers share rewards",
			4,
			&qbft.Config{
				ProposerPolicy: qbft.NewRoundRobinProposerPolicy(),
				Epoch:          1,
			},
			[]*big.Int{big.NewInt(4000), big.NewInt(3000), big.NewInt(2000), big.NewInt(1000)},
			[]uint64{1200000, 900000, 600000, 300000},
		},
		{
			"Stakers share rewards (validator set is subset of stakers)",
			2,
			&qbft.Config{
				ProposerPolicy: qbft.NewRoundRobinProposerPolicy(),
				Epoch:          1,
			},
			[]*big.Int{big.NewInt(4000), big.NewInt(6000), big.NewInt(2000), big.NewInt(1000)},
			[]uint64{1200000, 1800000, 0, 0},
		},
		{
			"Stakers share rewards, which sum of sharing does not equal to original amounts",
			4,
			&qbft.Config{
				ProposerPolicy: qbft.NewRoundRobinProposerPolicy(),
				Epoch:          1,
			},
			[]*big.Int{big.NewInt(239045), big.NewInt(7233), big.NewInt(732), big.NewInt(10)},
			[]uint64{2903145, 87843, 8889, 121}, // sum: 2999998
		},
		{
			"Stakers have zero staking amounts",
			4,
			&qbft.Config{
				ProposerPolicy: qbft.NewRoundRobinProposerPolicy(),
				Epoch:          1,
			},
			[]*big.Int{big.NewInt(0), big.NewInt(0), big.NewInt(0), big.NewInt(0)},
			[]uint64{0, 0, 0, 0},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Setup validators
			signers := newAccounts(len(tc.stakes))

			// Setup test chain genesis (non-Brioche config)
			c := new(fakeChain)
			c.chainConfig = params.TestChainConfig
			c.chainConfig.BriocheBlock = nil
			c.chainConfig.QBFT.BlockReward = (*math.HexOrDecimal256)(big.NewInt(3000000))
			state, _ := state.New(types.EmptyRootHash, state.NewDatabase(rawdb.NewMemoryDatabase()), nil)
			engine := NewEngine(tc.qbftConfig, common.Address{}, nil)
			parent := makeGenesis(signers)
			c.insertHeader(parent)

			// Change validator set
			extra, _ := types.ExtractQBFTExtra(parent)
			extra.EpochInfo.Validators = extra.EpochInfo.Validators[:tc.totValidators]
			slices.Reverse(extra.EpochInfo.Validators) // deterministic shuffle
			ApplyHeaderQBFTExtra(parent, WriteEpochInfo(extra.EpochInfo))

			// Proposer makes a block
			proposer := signers[0].addr
			h := makeHeader(parent)
			h.Coinbase = proposer
			c.insertHeader(h)

			staking := make(map[common.Address]*big.Int)
			for j, s := range signers {
				staking[s.addr] = tc.stakes[j]
			}

			getStakerInfo := func(addr common.Address) *govwbft.Staker {
				return &govwbft.Staker{
					Operator:  addr,
					Rewardee:  addr,
					Staking:   staking[addr],
					Delegated: big.NewInt(0),
				}
			}

			blockReward := c.Config().GetBlockReward(h.Number)
			origBlockReward := new(big.Int).Set(blockReward)
			engine.calculateRewards(
				c,
				h,
				makeRewardFunc(state, blockReward),
				getStakerInfo,
			)

			// Check QBFT config intact
			if c.Config().GetBlockReward(h.Number).Cmp(origBlockReward) != 0 {
				t.Errorf("expected block reward config mismatch: have %v, want %v", c.Config().GetBlockReward(h.Number), origBlockReward)
			}

			// Validate rewards
			left := new(big.Int).Set(origBlockReward)
			for j, r := range tc.expRewards {
				bal := state.GetBalance(signers[j].addr)
				if bal.CmpUint64(r) != 0 {
					t.Errorf("expected reward mismatch for staker %d: have %v, want %v", j, bal, r)
				}
				left.Sub(left, bal.ToBig())
			}
			if blockReward.Cmp(left) != 0 {
				t.Errorf("expected block reward left mismatch: have %v, want %v", left, blockReward)
			}
		})
	}
}

func makeGenesis(signers []account) *types.Header {
	header := &types.Header{
		Number:     big.NewInt(0),
		Time:       uint64(time.Now().UnixNano()),
		Difficulty: types.QBFTDefaultDifficulty,
	}

	e := new(types.EpochInfo)
	for i, s := range signers {
		e.Stakers = append(e.Stakers, &types.Staker{Addr: s.addr, Diligence: 1900000})
		e.Validators = append(e.Validators, uint32(i))
	}
	ApplyHeaderQBFTExtra(header, WriteEpochInfo(e))
	return header
}

func makeHeader(parent *types.Header) *types.Header {
	header := types.CopyHeader(parent)
	header.Number.Add(header.Number, big.NewInt(1))
	header.Time = uint64(time.Now().UnixNano())

	return header
}

func makePrepareSeal(h *types.Header, node account, round uint32) []byte {
	seal, err := crypto.Sign(qbftcore.PrepareSeal(h, round, qbftcore.SealTypePrepare), node.key)
	if err != nil {
		panic(err)
	}
	return seal
}

func makeCommitSeal(h *types.Header, node account, round uint32) []byte {
	seal, err := crypto.Sign(qbftcore.PrepareSeal(h, round, qbftcore.SealTypeCommit), node.key)
	if err != nil {
		panic(err)
	}
	return seal
}

func getEpochBlock(e *Engine, chain consensus.ChainHeaderReader, header *types.Header) *types.Header {
	config := chain.Config()
	for {
		header = chain.GetHeader(header.ParentHash, header.Number.Uint64()-1)
		if isEpoch, _, err := e.IsEpochBlockNumber(config, header.Number); err != nil {
			log.Crit("IsEpochBlockNumber failed", "number", header.Number, "err", err)
		} else if isEpoch {
			break
		}
	}

	return header
}

func TestIsEpochBlock(t *testing.T) {
	engine := NewEngine(nil, common.Address{}, nil)

	testCases := []struct {
		chainConfig         params.ChainConfig
		config              qbft.Config
		blockNumber         *big.Int
		expectedResult      bool
		expectedLatestEpoch *big.Int
		expectedError       error
	}{
		// case 1: no montblanc fork, zero block is an epoch block
		{
			params.ChainConfig{},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int),
			true,
			new(big.Int),
			nil,
		},
		// case 2: no montblanc fork, 1 block is not an epoch block
		{
			params.ChainConfig{},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(1),
			false,
			new(big.Int),
			nil,
		},
		// case 3: no montblanc fork, epoch - 1 block is not an epoch block
		{
			params.ChainConfig{},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(99),
			false,
			new(big.Int),
			nil,
		},
		// case 4: no montblanc fork, epoch block is an epoch block
		{
			params.ChainConfig{},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(100),
			true,
			new(big.Int).SetUint64(100),
			nil,
		},
		// case 5: no montblanc fork, epoch block * n is an epoch block
		{
			params.ChainConfig{},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(300),
			true,
			new(big.Int).SetUint64(300),
			nil,
		},
		// case 6: montblanc fork, error before fork
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(1),
			},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int),
			false,
			nil,
			qbftcommon.ErrIsNotWBFTBlock,
		},
		// case 7: montblanc fork, fork block is an epoch block
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(13),
			},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(13),
			true,
			new(big.Int).SetUint64(13),
			nil,
		},
		// case 8: montblanc fork, next of fork block is not an epoch block
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(13),
			},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(14),
			false,
			new(big.Int).SetUint64(13),
			nil,
		},
		// case 9: montblanc fork, fork block + epoch is an epoch block
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(13),
			},
			qbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(113),
			true,
			new(big.Int).SetUint64(113),
			nil,
		},
		// case 10: montblanc fork, transition exist, before transition
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(1000),
			},
			qbft.Config{
				Epoch: 100,
				Transitions: []params.Transition{
					{Block: new(big.Int).SetUint64(1101), EpochLength: 200},
				},
			},
			new(big.Int).SetUint64(1100), // before transition
			true,
			new(big.Int).SetUint64(1100),
			nil,
		},
		// case 11: montblanc fork, transition exist, just on transition
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(1000),
			},
			qbft.Config{
				Epoch: 100,
				Transitions: []params.Transition{
					{Block: new(big.Int).SetUint64(1100), EpochLength: 200},
				},
			},
			new(big.Int).SetUint64(1100), // on transition
			true,
			new(big.Int).SetUint64(1100),
			nil,
		},
		// case 12: montblanc fork, transition exist, after transition, applied new epoch length
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(1000),
			},
			qbft.Config{
				Epoch: 100,
				Transitions: []params.Transition{
					{Block: new(big.Int).SetUint64(1100), EpochLength: 200},
				},
			},
			new(big.Int).SetUint64(1200),
			false,
			new(big.Int).SetUint64(1100),
			nil,
		},
		// case 13: edge case; transition before montblanc fork?
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(1000),
			},
			qbft.Config{
				Epoch: 100,
				Transitions: []params.Transition{
					{Block: new(big.Int).SetUint64(950), EpochLength: 50},
				},
			},
			new(big.Int).SetUint64(1050),
			true,
			new(big.Int).SetUint64(1050),
			nil,
		},
		// case 14: montblanc fork, transitions exist, after transition, applied new epoch length
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(1000),
			},
			qbft.Config{
				Epoch: 100,
				Transitions: []params.Transition{
					{Block: new(big.Int).SetUint64(1100), EpochLength: 200},
					{Block: new(big.Int).SetUint64(1300), EpochLength: 100},
				},
			},
			new(big.Int).SetUint64(1200),
			false,
			new(big.Int).SetUint64(1100),
			nil,
		},
		// case 15: montblanc fork, transitions exist, after transitions, applied new epoch length
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(1000),
			},
			qbft.Config{
				Epoch: 100,
				Transitions: []params.Transition{
					{Block: new(big.Int).SetUint64(1100), EpochLength: 200},
					{Block: new(big.Int).SetUint64(1300), EpochLength: 50},
				},
			},
			new(big.Int).SetUint64(1350),
			true,
			new(big.Int).SetUint64(1350),
			nil,
		},
		// case 16: montblanc fork, transitions exist, after transitions, applied new epoch length
		{
			params.ChainConfig{
				MontBlancBlock: new(big.Int).SetUint64(1000),
			},
			qbft.Config{
				Epoch: 100,
				Transitions: []params.Transition{
					{Block: new(big.Int).SetUint64(1100), EpochLength: 10},
					{Block: new(big.Int).SetUint64(1300), EpochLength: 50},
				},
			},
			new(big.Int).SetUint64(1310),
			false,
			new(big.Int).SetUint64(1300),
			nil,
		},
	}

	for i, tc := range testCases {
		testConfig := tc.config
		engine.cfg = &testConfig
		if r, epoch, err := engine.IsEpochBlockNumber(&tc.chainConfig, tc.blockNumber); err != nil {
			if !errors.Is(err, tc.expectedError) {
				t.Errorf("[case %d] unexpected error: have %v, want %v", i+1, err, tc.expectedError)
			}
			if epoch != nil {
				t.Errorf("[case %d] unexpected epoch: have %v, want nil", i+1, epoch)
			}
		} else {
			if r != tc.expectedResult {
				t.Errorf("[case %d] unexpected result: have %v, want %v", i+1, r, tc.expectedResult)
			}
			if epoch.Cmp(tc.expectedLatestEpoch) != 0 {
				t.Errorf("[case %d] unexpected epoch: have %v, want %v", i+1, epoch, tc.expectedLatestEpoch)
			}
		}
	}
}
