name: "Dev Branch Release"

on:
  push:
    tags:
      - v*  # action for tag starts with v

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Setup packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libjemalloc-dev liblz4-dev libsnappy-dev libzstd-dev libudev-dev
          sudo apt remove -y bzip2 libbz2-dev zlib1g-dev

      - name: Build binary
        run: make all

      - name: Set version
        run: |
          GETH_VERSION=$(build/bin/gwemix version | awk '/^Version/{ print $2 }')
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-8)
          TAG_NAME="${{ github.ref_name }}"
          echo "RELEASE_VERSION=${GETH_VERSION}-${COMMIT_HASH}" >> "$GITHUB_ENV"
          echo "TAG_NAME=${TAG_NAME}" >> "$GITHUB_ENV"
          echo "Creating release for version: ${GETH_VERSION}-${COMMIT_HASH} with tag: ${TAG_NAME}"

      - name: Create tarball
        run: |
          mkdir -p release
          cp build/bin/* release/
          cd release
          tar -czf "gwemix-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz" *
          cd ..
          ls -la release/
          mv "release/gwemix-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz" .
          ls -la gwemix-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: WEMIX Build (${{ env.RELEASE_VERSION }})
          tag_name: ${{ env.TAG_NAME }}
          draft: true
          files: gwemix-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz
